//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalloWCF.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obst", Namespace="http://schemas.datacontract.org/2004/07/HalloWCF")]
    [System.SerializableAttribute()]
    public partial class Obst : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FarbeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HaltbarBisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KCalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PreisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Farbe {
            get {
                return this.FarbeField;
            }
            set {
                if ((object.ReferenceEquals(this.FarbeField, value) != true)) {
                    this.FarbeField = value;
                    this.RaisePropertyChanged("Farbe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HaltbarBis {
            get {
                return this.HaltbarBisField;
            }
            set {
                if ((this.HaltbarBisField.Equals(value) != true)) {
                    this.HaltbarBisField = value;
                    this.RaisePropertyChanged("HaltbarBis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KCal {
            get {
                return this.KCalField;
            }
            set {
                if ((this.KCalField.Equals(value) != true)) {
                    this.KCalField = value;
                    this.RaisePropertyChanged("KCal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preis {
            get {
                return this.PreisField;
            }
            set {
                if ((this.PreisField.Equals(value) != true)) {
                    this.PreisField = value;
                    this.RaisePropertyChanged("Preis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Verdoppeln", ReplyAction="http://tempuri.org/IService1/VerdoppelnResponse")]
        int Verdoppeln(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Verdoppeln", ReplyAction="http://tempuri.org/IService1/VerdoppelnResponse")]
        System.Threading.Tasks.Task<int> VerdoppelnAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetObst", ReplyAction="http://tempuri.org/IService1/GetObstResponse")]
        HalloWCF.Client.ServiceReference1.Obst[] GetObst();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetObst", ReplyAction="http://tempuri.org/IService1/GetObstResponse")]
        System.Threading.Tasks.Task<HalloWCF.Client.ServiceReference1.Obst[]> GetObstAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HalloWCF.Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HalloWCF.Client.ServiceReference1.IService1>, HalloWCF.Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public int Verdoppeln(int value) {
            return base.Channel.Verdoppeln(value);
        }
        
        public System.Threading.Tasks.Task<int> VerdoppelnAsync(int value) {
            return base.Channel.VerdoppelnAsync(value);
        }
        
        public HalloWCF.Client.ServiceReference1.Obst[] GetObst() {
            return base.Channel.GetObst();
        }
        
        public System.Threading.Tasks.Task<HalloWCF.Client.ServiceReference1.Obst[]> GetObstAsync() {
            return base.Channel.GetObstAsync();
        }
    }
}
